version: "3.9"

services:
  claude-blank-dev-env:
    build:
      context: .
      dockerfile: Dockerfile.claude
      args:
        ERLANG_VERSION: ${ERLANG_VERSION}
        ELIXIR_VERSION: ${ELIXIR_VERSION}
        ELIXIR_FULL_VERSION: ${ELIXIR_FULL_VERSION}
        KERL_CONFIGURE_OPTIONS: ${KERL_CONFIGURE_OPTIONS}
    environment:
      - CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
      - DISABLE_ERROR_REPORTING=1
      - DISABLE_TELEMETRY=1
      - USE_BUILTIN_RIPGREP=0
      - IS_SANDBOX=1
      - ERLANG_VERSION=${ERLANG_VERSION}
      - ELIXIR_VERSION=${ELIXIR_VERSION}
      - ELIXIR_FULL_VERSION=${ELIXIR_FULL_VERSION}
      - KERL_CONFIGURE_OPTIONS=${KERL_CONFIGURE_OPTIONS}
    volumes:
      - ./:/root/claude
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh_keys:/root/.ssh
    working_dir: /root/claude/projects
    stdin_open: true
    tty: true
    ports:
      - "3222:3222"
#    command: ["bash", "-l"]
    command: ["bash", "-c", "source /root/erlang/OTP-${ERLANG_VERSION}/activate && source /root/.kiex/elixirs/elixir-${ELIXIR_FULL_VERSION}.env && claude --dangerously-skip-permissions"]

volumes:
  ssh_keys:
